# HW01 <font color=red>(제출기한-3월30일 일요일 자정)</font>
---
NumPy 이해도 평가를 위한 문제입니다.
다음 사항을 주의해서 제출하기 바랍니다.

- 각 문제에 대한 답안을 <font color=red>'답안을 작성하시오'</font>라고 적힌 <font color=red>한 코드셀 내</font>에 작성하며 셀 내에서 여러줄로 작성해도 무방합니다.
- 셀을 추가하거나 셀을 삭제하지 않습니다. 예: (<font color=red>'지우지 마시오'</font> 셀 등)
- 출력결과가 미리 제시된 셀(<font color=red>'예시 실행결과를 참조하시오.'</font>라고 표시된 셀)을 참고합니다.
- Loop를 사용하지 말고 ufunc을 활용합니다.
- 수업시간 배운 내용만을 사용하여 코드를 작성합니다.
- 문제나 제출방법에 대한 질문이 있을 경우 제출전 UCLASS 등을 통해 반드시 미리 확인합니다.

> 제출방법

- ULMS HW1 제출란에 <font color=red>'HW01-학번.ipynb'</font>(본인학번을 기입)을 기한내 업로드합니다.


### 가정
- 아래에서 생성된 _score_ 변수는 $20 \times 4$ 크기의 2차원 numpy array이다.
- 이는 10명 학생의 국어, 영어, 수학, 사회 점수(1번째부터 3번째 열 순서)를 각각 나타낸다. (0점~100점)

In [28]:
### 지우지 마시오.
import numpy as np
rng=np.random.RandomState(765)
score=rng.randint(20, 101,(10,4))
score

array([[49, 24, 66, 47],
       [90, 99, 80, 39],
       [20, 58, 38, 85],
       [36, 27, 62, 56],
       [84, 37, 28, 49],
       [75, 75, 26, 44],
       [22, 60, 26, 45],
       [85, 30, 99, 69],
       [40, 25, 81, 57],
       [45, 98, 64, 57]])

### 문제1
가장 마지막 학생의 수학 점수가 64점이 아니라 46점이라고 한다.

이렇게 *score* 배열을 수정하기 위한 코드를 작성하시오.

In [29]:
### 답안을 작성하시오.
score[9,3]=46

In [30]:
### 예시 실행결과를 참조하시오.
score

array([[49, 24, 66, 47],
       [90, 99, 80, 39],
       [20, 58, 38, 85],
       [36, 27, 62, 56],
       [84, 37, 28, 49],
       [75, 75, 26, 44],
       [22, 60, 26, 45],
       [85, 30, 99, 69],
       [40, 25, 81, 57],
       [45, 98, 64, 46]])

### 문제2
위 결과 이후 채점에 오류가 발견되어 모든 학생들의 영어점수를 5점씩 줄여야 한다고 한다. 이렇게 *score* 배열을 수정하기 위한 코드를 작성하시오.

In [31]:
### 답안을 작성하시오.
score[:,1]-=5

In [32]:
### 예시 실행결과를 참조하시오.
score

array([[49, 19, 66, 47],
       [90, 94, 80, 39],
       [20, 53, 38, 85],
       [36, 22, 62, 56],
       [84, 32, 28, 49],
       [75, 70, 26, 44],
       [22, 55, 26, 45],
       [85, 25, 99, 69],
       [40, 20, 81, 57],
       [45, 93, 64, 46]])

### 문제3
새로운 음악, 미술 과목의 시험 점수가 다음 _score\_add_ 변수에 주어진다. 이를 _score_ 변수 데이터에 덧붙여 총 6개 과목의 데이터를 *score_all*변수에 다시 저장하고자 한다. 이를 위한 코드를 작성하시오.

In [33]:
### 지우지 마시오.
score_add=rng.randint(20, 101,(10,2))
score_add

array([[98, 46],
       [36, 91],
       [72, 37],
       [35, 98],
       [66, 96],
       [66, 85],
       [43, 37],
       [81, 24],
       [94, 91],
       [98, 62]])

In [75]:
### 답안을 작성하시오.
score_all = np.concatenate((score,score_add),axis=1)
score_all

array([[49, 19, 66, 47, 98, 46],
       [90, 94, 80, 39, 36, 91],
       [20, 53, 38, 85, 72, 37],
       [36, 22, 62, 56, 35, 98],
       [84, 32, 28, 49, 66, 96],
       [75, 70, 26, 44, 66, 85],
       [22, 55, 26, 45, 43, 37],
       [85, 25, 99, 69, 81, 24],
       [40, 20, 81, 57, 94, 91],
       [45, 93, 64, 46, 98, 62]])

In [35]:
### 예시 실행결과를 참조하시오.
score_all

array([[49, 19, 66, 47, 98, 46],
       [90, 94, 80, 39, 36, 91],
       [20, 53, 38, 85, 72, 37],
       [36, 22, 62, 56, 35, 98],
       [84, 32, 28, 49, 66, 96],
       [75, 70, 26, 44, 66, 85],
       [22, 55, 26, 45, 43, 37],
       [85, 25, 99, 69, 81, 24],
       [40, 20, 81, 57, 94, 91],
       [45, 93, 64, 46, 98, 62]])

### 문제4
위 결과 *score_all* array에 대해 과목별 평균점수를 뜻하는 _avg\_subject_ array(1차원)를 구하는 코드를 작성하시오.

In [76]:
### 답안을 작성하시오.
avg_subject = np.average(score_all,axis=0)

In [37]:
### 예시 실행결과를 참조하시오.
avg_subject

array([54.6, 48.3, 57. , 53.7, 68.9, 66.7])

### 문제5
비슷하게 *score* array에 대해 학생별 평균점수를 뜻하는 _avg\_student_ array(1차원)를 구하는 코드를 작성하시오.

In [46]:
### 답안을 작성하시오.
avg_student = np.average(score_all,axis=1)

In [61]:
### 예시 실행결과를 참조하시오.
avg_student

array([54.16666667, 71.66666667, 50.83333333, 51.5       , 59.16666667,
       61.        , 38.        , 63.83333333, 63.83333333, 68.        ])

### 문제6
각 점수가 해당과목의 평균으로부터 얼마나 차이가 나는지(이를 편차라고 한다.)를 나타내는 _score\_dev_ array(2차원)를 생성하시오.
- score_dev의 shape는 score의 shape와 동일하다. 즉 score_dev.shape=(20, 6)
- 만약 어떤 학생의 국어 점수가 30점이고 전체 학생의 국어 평균이 45점이면 그 차이(편차)는 $30-45=-15$ 점이다.

---
참고) _score\_dev_ 의 axis=0 방향 평균값이 어떻게 될 지 생각해 보자.


In [82]:
### 답안을 작성하시오.
score_dev = score_all - np.mean(score_all, axis=0)

In [83]:
### 예시 실행결과를 참조하시오.
score_dev

array([[ -5.6, -29.3,   9. ,  -6.7,  29.1, -20.7],
       [ 35.4,  45.7,  23. , -14.7, -32.9,  24.3],
       [-34.6,   4.7, -19. ,  31.3,   3.1, -29.7],
       [-18.6, -26.3,   5. ,   2.3, -33.9,  31.3],
       [ 29.4, -16.3, -29. ,  -4.7,  -2.9,  29.3],
       [ 20.4,  21.7, -31. ,  -9.7,  -2.9,  18.3],
       [-32.6,   6.7, -31. ,  -8.7, -25.9, -29.7],
       [ 30.4, -23.3,  42. ,  15.3,  12.1, -42.7],
       [-14.6, -28.3,  24. ,   3.3,  25.1,  24.3],
       [ -9.6,  44.7,   7. ,  -7.7,  29.1,  -4.7]])

### 문제7
위 *avg_student*를 이용하여 전체과목 평균점수를 기준으로 1등과 10등을 한 학생들이 몇 번째 학생인지를 각각 *student_best*와 *student_worst*에 각각 저장하시오.
- 결과값은 1이상 10이하의 자연수이다.

In [85]:
### 답안을 작성하시오.
student_best = np.argmax(avg_student)+1
student_worst = np.argmin(avg_student)+1

In [86]:
### 예시 실행결과를 참조하시오.
student_best, student_worst

(np.int64(2), np.int64(7))

### 문제8
위 avg_student를 이용하여 전체 학생의 평균점수를 구하여 _avg\_total_ 변수에 저장하시오.

In [87]:
### 답안을 작성하시오.
avg_total = np.mean(avg_student)

In [88]:
### 예시 실행결과를 참조하시오.
avg_total

np.float64(58.2)

### 문제9
전체 평균 점수(_avg\_total_) 보다 높은 평균 점수를 얻은 학생의 수를 구하여 _no\_student\_high_ 변수에 저장하시오.  

In [89]:
### 답안을 작성하시오.
no_student_high = np.sum(avg_student > avg_total)

In [90]:
### 예시 실행결과를 참조하시오.
no_student_high

np.int64(6)

### 문제10
수학점수가 국어점수와 영어점수보다 모두 더 높은 학생 수를 구하여 _no\_student\_math_ 변수에 저장하시오.


In [91]:
### 답안을 작성하시오.
no_student_math = np.sum((score_all[:,2] > score_all[:,0]) & (score_all[:,2]>score_all[:,1]))

In [92]:
### 예시 실행결과를 참조하시오.
no_student_math

np.int64(4)